### ISSUE TITLE
Requesting Patch for ALC888S

### ISSUE THREAD

**Issue by Niresh12495** [toleda/audio_ALCInjection#1]
I Crawled All Over The Internet For The Latest Kext for ALC888S
Once I Was Able to Find out a Patched AppleHDA I Have Been Using That Version for More-than Two Years but 
I Need a New Version
 as You are an Expert May Be You Can Patch Can You

Files Included
Working Kext of ALC 888S
HDA Enabler
Linux Codec Dump of ALC888S
DSDT Code That Works 
http://cl.ly/12462G361F1w/ALC%20888S.7z

**Comment by toleda** [comment]
The ALC888S is the same as the ALC888.  Try this kext: http://www.insanelymac.com/forum/files/file/130-realtek-alc888-applehda-audio/

Use dsdt/HDEF/layout-id: 0x01, 0x00, 0x00, 0x00
or use an Audio_ID: 1 audio enabler from https://github.com/toleda/audio_ALCInjection

**Comment by Niresh12495** [comment]
Well i Tried What You Said With HDAEnabler and DSDT Edit
Both Didn't Work Out 

and Also The Kexts You Provided Me Looks Similar to The ALC 888 v100202 Legacy of Multibeast Tried Them too Not Working 
(I know that you provide tonymac those kexts)

**Comment by toleda** [comment]
Attach IOReg_v2.1/File/Save a Copy As..  for each AppleHDA.kext you tried.

**Comment by Niresh12495** [comment]
How About IOReg 2.0 (2.0b1)
Other Versions 3.0 Crashed i Dont Know Why

**Comment by toleda** [comment]
Download IOReg zip from this repo.

**Comment by Niresh12495** [comment]
Here is the dsdt attached 
with EL Capitan there is no audio for 888S
Layout id was marked as 4 in DSDT?
Here is the link to DSDT + Working Kext (Upto Yosemite) + Linux Codec Dump
http://cl.ly/dQhb

**Comment by toleda** [comment]
Your 888S is a 888_v100202, 888 Legacy.  Your injection is not correct, dsdt and enabler use layout-d=12, remove. Override...., no idea, remove.  888 Legacy uses layout-id 1 or 2 only. Install proper layout-id injection and confirm 888 Legacy with either script, realtekALC or cloverALC.
