### ISSUE TITLE
Minor suggestions

### ISSUE THREAD

**Issue by fl0eb** [toleda/audio_ALCInjection#3]
Hi Toleda,

thanks for your great work.

Maybe you want to remove the x99 duplicate in:
https://github.com/toleda/audio_ALCInjection/tree/master/ssdt_hdef

Also for the x99 aml I had to remove the HDEF. in front of the _DSM in my SSDT:
`Method (HDEF._DSM, 4, NotSerialized)` -> `Method (_DSM, 4, NotSerialized)`

as it is already in `Device (HDEF)` it is too much, isn't it?

Regards

**Comment by toleda** [comment]
Done.
No need for the x99-azal ssdt with HDEF, remove.
